# Generated by Django 5.2.3 on 2025-08-13 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0002_remove_participantes_telefone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantes',
            name='status',
        ),
    ]
