# Generated by Django 5.2.3 on 2025-08-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0003_remove_participantes_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantes',
            name='cadastro',
            field=models.CharField(choices=[('1', 'Whatsapp'), ('2', 'Hotsite')], default='2', max_length=1),
        ),
        migrations.AddField(
            model_name='participantes',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participantes',
            name='status',
            field=models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo')], default='1', max_length=1),
        ),
    ]
