# Generated by Django 5.2.3 on 2025-08-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0004_participantes_cadastro_participantes_complemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantes',
            name='aceita_info_bombril',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participantes',
            name='aceita_msg_whatsapp',
            field=models.BooleanField(default=False),
        ),
    ]
