<<<<<<< HEAD
# Generated by Django 5.2.3 on 2025-08-15 02:13

=======
# Generated by Django 5.2.3 on 2025-08-15 03:28

import django.utils.timezone
>>>>>>> main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0005_participantes_aceita_info_bombril_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantes',
            name='data_cadastro',
<<<<<<< HEAD
            field=models.DateField(auto_now_add=True, default='2025-08-14'),
=======
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
>>>>>>> main
            preserve_default=False,
        ),
    ]
