# Generated by Django 5.2.3 on 2025-08-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log_participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log_usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
