# Generated by Django 5.2.3 on 2025-08-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupons', '0004_serie_nome_serie_serie_numero_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='numero_documento',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
