# Generated by Django 5.2.3 on 2025-08-14 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupons', '0005_alter_cupom_numero_documento'),
        ('cupons', '0005_alter_cupom_tipo_envio'),
    ]

    operations = [
    ]
