# Generated by Django 5.2.3 on 2025-08-15 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupons', '0006_merge_20250814_0047'),
        ('skus_validos', '0002_skus_validos_is_acelerador'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='sku_validado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='skus_validos.skus_validos'),
        ),
    ]
