name: Deploy Django to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Google Cloud VM
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar chave SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Executar comandos de deploy via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
          cd ~/gestor_campanhax
          git pull origin main

          source venv/bin/activate
          pip install -r requirements.txt

          python manage.py migrate
          python manage.py collectstatic --noinput

          sudo supervisorctl restart gestor
        EOF
