# Generated by Django 5.2.3 on 2025-08-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skus_validos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skus_validos',
            name='is_acelerador',
            field=models.BooleanField(default=False),
        ),
    ]
