# Generated by Django 5.2.3 on 2025-08-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sorteios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('1', 'Aberto'), ('2', 'Finalizado')], max_length=1, null=True)),
                ('resultado_sorteio', models.CharField(max_length=200)),
            ],
        ),
    ]
