# Generated by Django 5.2.3 on 2025-08-14 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='pergunta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='usuario_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sorteios',
            name='data_cadastro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='',
            name='data_sorteio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='',
            name='hora_cadastro',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sorteios',
            name='hora_sorteio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sorteios',
            name='usuario_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
