# Generated by Django 5.2.3 on 2025-08-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0002_faq_data_faq_hora_faq_pergunta_faq_usuario_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_data_cupom_aceito', models.DateField(blank=True, null=True)),
                ('min_data_cupom_aceito', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
