# Generated by Django 5.2.3 on 2025-08-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0003_regras'),
    ]

    operations = [
        migrations.AddField(
            model_name='regras',
            name='qtd_cupom_dia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
