# Generated by Django 5.2.3 on 2025-08-16 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0005_sorteios_delete_soteios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorteios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateField(blank=True, null=True)),
                ('hora_cadastro', models.TimeField(blank=True, null=True)),
                ('data_sorteio', models.DateField(blank=True, null=True)),
                ('hora_sorteio', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Aberto'), ('2', 'Finalizado')], max_length=1, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('resultado_sorteio', models.CharField(max_length=200)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
